### ISSUE TITLE
Zipato Micromodule Motor Controller Support

### ISSUE THREAD

**Issue by h8pewou** [SmartThingsCommunity/SmartThingsPublic#16470] opened 2019-12-28 14:29 UTC
Zipato Micromodule Motor Controllers ([https://www.zipato.com/product/micro-module-motor-controller](https://www.zipato.com/product/micro-module-motor-controller)) seem to work fine with the standard [Z-Wave Window Shade](https://github.com/SmartThingsCommunity/SmartThingsPublic/blob/master/devicetypes/smartthings/zwave-window-shade.src/zwave-window-shade.groovy) code except for one thing: levels may be implemented incorrectly in the Zipato device, they are inverted. As an example 20% is reported as 80%, open is reported as closed. 

Is there an easy way to fix this?

`fingerprint mfr: "0131", prod: "0001", model: "0015", deviceJoinName: "Zipato Shutter"`

**Comment by h8pewou** [comment] 2020-01-01 14:11
I've made some minor changes to the original code and it seem to be working fine, see [zipato-shutter.groovy](https://raw.githubusercontent.com/h8pewou/SmartThingsPublic/master/devicetypes/h8pewou/zipato-shutter.src/zipato-shutter.groovy).

Is it possible to execute this locally?

**Comment by monninn** [comment] 2020-04-01 10:39
Duplicate of #

**Comment by h8pewou** [comment] 2021-02-23 11:58
> Zipato Micromodule Motor Controllers (https://www.zipato.com/product/micro-module-motor-controller) seem to work fine with the standard [Z-Wave Window Shade](https://github.com/SmartThingsCommunity/SmartThingsPublic/blob/master/devicetypes/smartthings/zwave-window-shade.src/zwave-window-shade.groovy) code except for one thing: levels may be implemented incorrectly in the Zipato device, they are inverted. As an example 20% is reported as 80%, open is reported as closed.
> 
> Is there an easy way to fix this?
> 
> `fingerprint mfr: "0131", prod: "0001", model: "0015", deviceJoinName: "Zipato Shutter"`

Answering my own question: switching the the NC1 and NO1 wires fixes this issue. In case if that's not an option, this file may work just fine: https://raw.githubusercontent.com/h8pewou/SmartThingsPublic/master/devicetypes/h8pewou/zipato-shutter.src/zipato-shutter.groovy

**Closed as completed** 2021-02-23 11:58 UTC
